name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  provider: ^6.0.5
  quickalert: ^1.0.1
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - lib/assets/page-1/images/battery.png
    - lib/assets/page-1/images/email.png
    - lib/assets/page-1/images/telepon.png
    - lib/assets/page-1/images/loc.png
    - lib/assets/page-1/images/cellular-connection.png
    - lib/assets/page-1/images/icons.png
    - lib/assets/page-1/images/icons-Umo.png
    - lib/assets/page-1/images/icons-jhj.png
    - lib/assets/page-1/images/cellular-connection-cTj.png
    - lib/assets/page-1/images/wifi.png
    - lib/assets/page-1/images/frame-969-bg.png
    - lib/assets/page-1/images/frame-969-bg-8Wu.png
    - lib/assets/page-1/images/frame-969-bg-xXB.png
    - lib/assets/page-1/images/frame-969-bg-85X.png
    - lib/assets/page-1/images/icons-card-yes-24.png
    - lib/assets/page-1/images/frame-969-bg-6NM.png
    - lib/assets/page-1/images/icons-Cb3.png
    - lib/assets/page-1/images/frame-969-bg-sFF.png
    - lib/assets/page-1/images/frame-969-bg-FuK.png
    - lib/assets/page-1/images/battery-T5K.png
    - lib/assets/page-1/images/image-14.png
    - lib/assets/page-1/images/battery-G2V.png
    - lib/assets/page-1/images/image-14-JBb.png
    - lib/assets/page-1/images/unsplash-5ks7t3gs3ca.png
    - lib/assets/page-1/images/image-14-1PP.png
    - lib/assets/page-1/images/wifi-6d7.png
    - lib/assets/page-1/images/image-14-4B3.png
    - lib/assets/page-1/images/wifi-oNy.png
    - lib/assets/page-1/images/frame-1014.png
    - lib/assets/page-1/images/battery-RMb.png
    - lib/assets/page-1/images/cellular-connection-irV.png
    - lib/assets/page-1/images/image-19-bg.png
    - lib/assets/page-1/images/frame-969-bg-YJm.png
    - lib/assets/page-1/images/cellular-connection-8q7.png
    - lib/assets/page-1/images/frame-969-bg-uwf.png
    - lib/assets/page-1/images/frame-969-bg-zN5.png
    - lib/assets/page-1/images/wifi-UQ1.png
    - lib/assets/page-1/images/frame-969-bg-jow.png
    - lib/assets/page-1/images/image-14-vjK.png
    - lib/assets/page-1/images/frame-969-bg-NZF.png
    - lib/assets/page-1/images/image-14-uiZ.png
    - lib/assets/page-1/images/image-14-cJd.png
    - lib/assets/page-1/images/image-14-xdP.png
    - lib/assets/page-1/images/image-14-Zay.png
    - lib/assets/page-1/images/frame-969-bg-E8H.png
    - lib/assets/page-1/images/frame-969-bg-Gam.png
    - lib/assets/page-1/images/image-14-unZ.png
    - lib/assets/page-1/images/mask-group.png
    - lib/assets/page-1/images/image-14-5jw.png
    - lib/assets/page-1/images/home-bg.png
    - lib/assets/page-1/images/image-14-LJV.png
    - lib/assets/page-1/images/image-14-zQq.png
    - lib/assets/page-1/images/image-16.png
    - lib/assets/page-1/images/home-bg-r8h.png
    - lib/assets/page-1/images/image-19.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
